import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-white">
          <div className="mx-auto max-w-7xl py-16 px-4 sm:py-24 sm:px-6 lg:px-8">
            <div className="text-center">
              <p className="mt-1 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl lg:text-6xl">
                Next.js with tailwind starter template
              </p>
              <p className="mx-auto mt-5 max-w-xl text-xl text-gray-500">
                Run <code className="bg-gray-200 px-2 py-1 rounded-md italic">npm run dev</code> to start server on <code className="bg-gray-200 px-2 py-1 rounded-md italic">localhost:3000</code>
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
